# Generated by Django 4.1.5 on 2023-02-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_folder_folder_in_folder_alter_file_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_in_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_within', to='mainapp.folder'),
        ),
    ]
