# Generated by Django 4.1.5 on 2023-02-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_folder_folder_in_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder_in_folder',
            new_name='folder',
        ),
    ]
