# Generated by Django 4.1.5 on 2023-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_folder_in_folder_folder_folder'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('folder', 'name'), name='folder_within'),
        ),
    ]
