# Generated by Django 4.1.5 on 2023-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_folder_folder_within'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='folder_within',
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('folder', 'name'), name='unique_folder_within'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_folder_dash'),
        ),
    ]
