# Generated by Django 4.1.5 on 2023-02-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_folder_unique_folder_dash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
